name: Build and Deploy Custom AMI

on:
  pull_request:
    types: [closed]
  push:
    branches:
      - '*'

jobs:
  test_and_package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run integration tests
        run: npm test

      - name: Package application with dependencies
        run: |
          mkdir -p build-artifacts
          zip -r build-artifacts/app-package.zip .  # Zip the entire app, including node_modules

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        id: setup
        with: 
          version: 1.11.2
                   
      - name: Run `packer init`
        id: init
        run: "packer init ./packer/main.pkr.hcl"
     
      - name: Build custom AMI with Packer
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}
        run: |
          PACKER_LOG=1 packer build -var "artifact_path=./build-artifacts/app-package.zip" -var "aws_region=${{ vars.AWS_REGION }}" ./packer/main.pkr.hcl
