name: Node.js Integration Tests with PostgreSQL

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U testuser"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm install
        continue-on-error: false # Ensure this step fails on error

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h 127.0.0.1 -p 5432 -U testuser; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 1
          done
        continue-on-error: false # Fail if PostgreSQL is not ready

      - name: Set environment variables for database
        run: |
          echo "DB_HOST=127.0.0.1" >> $GITHUB_ENV
          echo "DB_PORT=5432" >> $GITHUB_ENV
          echo "DB_USER=testuser" >> $GITHUB_ENV
          echo "DB_PASSWORD=testpassword" >> $GITHUB_ENV
          echo "DB_NAME=testdb" >> $GITHUB_ENV

      - name: Run tests
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 5432
          DB_USER: testuser
          DB_PASSWORD: testpassword
          DB_NAME: testdb
        run: |
          echo "Waiting a few seconds for PostgreSQL to fully initialize..."
          sleep 5
          npm test
        continue-on-error: false # Ensure this step fails on test failure
